# -*- coding: utf-8 -*-
"""
Revisao OCR de data/text/anjos-a-cidade-de-prata.txt

Aplica correcoes de erros OCR detectados na revisao textual.
Gera anjos-a-cidade-de-prata.corrigido.txt e imprime estatisticas.

As correcoes estao agrupadas por categoria. Strings unicas (alta confianca)
sao substituidas globalmente; nomes proprios e termos do sistema (Daemon)
sao preservados conforme o glossario do livro.
"""
from __future__ import annotations
import re
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
SRC = BASE / "data" / "text" / "anjos-a-cidade-de-prata.txt"
OUT = BASE / "data" / "text" / "anjos-a-cidade-de-prata.corrigido.txt"

# (errado, correto) - substituicoes literais de alta confianca.
# Mantidas em ordem; aplicadas globalmente.
REPLACEMENTS: list[tuple[str, str]] = [
    # --- Cabecalhos / titulos de capitulo (mojibake de letras especiais) ---
    ("INTR0DUCÃ0", "INTRODUÇÃO"),
    ("© QUE E RPG ?", "O QUE É RPG?"),
    ("G©Ncerres BÁsices", "CONCEITOS BÁSICOS"),
    ("A aoADfi oe PRATA", "A CIDADE DE PRATA"),
    ("A HisréRiA De PARADÍSIA", "A HISTÓRIA DE PARADÍSIA"),
    ("0 cetnec®", "O CENÁRIO"),
    ("A PaimeiRA REBELIÀ®", "A PRIMEIRA REBELIÃO"),
    ("©LYfflPUS", "OLYMPUS"),
    ("HlETRéPeus", "METRÓPOLIS"),
    ("A CIDADE DeURADA DE RA", "A CIDADE DOURADA DE RA"),
    ("A ÁRven.6 DA VIDA, A QUABALUA E ®s SEPHIRAH",
     "A ÁRVORE DA VIDA, A QUABALAH E OS SEPHIRAH"),
    ("RATmARAN", "KATMARAN"),
    ("HÊRIUES, A fflAGlA E A SEGUNDA REBEUÃffi",
     "HERMES, A MAGIA E A SEGUNDA REBELIÃO"),
    ("ffi Diluvie", "O DILÚVIO"),
    ("As PiRAmiDEs", "AS PIRÂMIDES"),
    ("A GUERRA DE TRÓIA", "A GUERRA DE TRÓIA"),
    ("® Teime DE", "O TEMPLO DE JERUSALÉM"),
    ("ReniA E ©", "ROMA E O IMPÉRIO"),
    ("NASCimENT® DE JESUS", "NASCIMENTO DE JESUS"),
    ("A EXPANSA® DA CIDADE DE PRATA", "A EXPANSÃO DA CIDADE DE PRATA"),
    ("As CRUZADAS", "AS CRUZADAS"),
    ("A INQUISICÃ®", "A INQUISIÇÃO"),
    ("©s Heaéis G SANT©S", "OS HERÓIS E SANTOS"),
    ("A IDADE DAS TREVAS", "A IDADE DAS TREVAS"),
    ("A GUERRA oes cem AH©S", "A GUERRA DOS CEM ANOS"),
    ("A PfiSTS", "A PESTE"),
    ("J®ANNA D'ARC.", "JOANNA D'ARC"),
    ("A GUERRA DAS DUAS R®SAS", "A GUERRA DAS DUAS ROSAS"),
    ("ALEmANHA", "ALEMANHA"),
    ("A PCNÍNSULA IBÉRICA", "A PENÍNSULA IBÉRICA"),
    ("© N®V® mUND®", "O NOVO MUNDO"),
    ("A CACA ÀS BRUXAS", "A CAÇA ÀS BRUXAS"),
    ("A ÁPRICA", "A ÁFRICA"),
    ("A ReveLucA® INDUSTRIAL", "A REVOLUÇÃO INDUSTRIAL"),
    ("©S ÊSTADffiS UNIDffiS", "OS ESTADOS UNIDOS"),
    ("A Am ERIÇA D® SUL E CENTRAL", "A AMÉRICA DO SUL E CENTRAL"),
    ("© SÉCUL® XXI", "O SÉCULO XXI"),
    ("ATRIBUTeS", "ATRIBUTOS"),
    ("CABECALH®", "CABEÇALHO"),
    ("PERÍCIAS cem ARHIAS", "PERÍCIAS COM ARMAS"),
    ("PQDERES ANGELICAIS", "PODERES ANGELICAIS"),
    ("APRIin®RAinENT®S", "APRIMORAMENTOS"),
    ("QuACÃe DG PfiRS©NAGfiNS", "CRIAÇÃO DE PERSONAGENS"),
    ("ATRIBUTOS BÁsices", "ATRIBUTOS BÁSICOS"),
    ("ATRIBUT©S Físices", "ATRIBUTOS FÍSICOS"),
    ("ATRIBUT®S HIENTAIS", "ATRIBUTOS MENTAIS"),
    ("NúmgRes DÊ TBSTE", "NÚMEROS DE TESTE"),
    ("N®VAS PERÍCIAS", "NOVAS PERÍCIAS"),
    ("C0RP0RÊ", "CORPORE"),
    ("©RGANIZACÃ0", "ORGANIZAÇÃO"),
    ("©RGANIZACAe", "ORGANIZAÇÃO"),
    ("©RGANIZACA©", "ORGANIZAÇÃO"),
    ("©RGANIZACÃe", "ORGANIZAÇÃO"),
    ("CAfflPANHA", "CAMPANHA"),
    ("CAmPANHA", "CAMPANHA"),
    ("CAIHPANHAS", "CAMPANHAS"),
    ("CAHIPANHAS", "CAMPANHAS"),
    ("PeoERfis ÚNices", "PODERES ÚNICOS"),
    ("Peo6R.es ÚNIC©S", "PODERES ÚNICOS"),
    ("PODERES ÚNices", "PODERES ÚNICOS"),
    ("P©DSRÊS ÚNICQS", "PODERES ÚNICOS"),
    ("P0DSRÊS ÚNIC©S", "PODERES ÚNICOS"),
    ("PeDÊRfis ÚNices", "PODERES ÚNICOS"),
    ("PeoERes ÚNices", "PODERES ÚNICOS"),
    ("PffiDBRes ÚNices", "PODERES ÚNICOS"),
    ("PffiDERfiS ÚN!C©S", "PODERES ÚNICOS"),
    ("P0DERÊS ÚNICffiS D®S ANJfflS", "PODERES ÚNICOS DOS ANJOS"),
    ("P©DfiRfiS ÚNIC©S", "PODERES ÚNICOS"),
    ("P0D6RES ÚNIC0S", "PODERES ÚNICOS"),
    ("UNICSS", "ÚNICOS"),
    ("CAPTARfi", "CAPTARE"),
    ("RfitíPÊRfiS", "RECÍPERES"),
    ("AR.meiR.es", "ARMEIROS"),
    ("HlAGffiS", "MAGOS"),
    ("BURffiCRATAS", "BUROCRATAS"),
    ("NimBus", "NIMBUS"),
    ("©RI G E m", "ORIGEM"),
    ("©RIGEffl", "ORIGEM"),
    ("QUERUBINS", "QUERUBINS"),
    ("TaeNes", "TRONOS"),
    ("DemiNACôes", "DOMINAÇÕES"),
    ("P0TÊNCIAS", "POTÊNCIAS"),
    ("VIRTUDES", "VIRTUDES"),
    ("PRINCIPAD0S", "PRINCIPADOS"),
    ("ARCA N [as e AN;®S", "ARCANJOS E ANJOS"),
    ("SERAFINS", "SERAFINS"),
    ("AumeNTe DE ATRiBures", "AUMENTO DE ATRIBUTOS"),
    ("ASAS ASTRAIS", "ASAS ASTRAIS"),
    ("BARD®", "BARDO"),
    ("BfiNCÃ®", "BÊNÇÃO"),
    ("CefflBATÊ", "COMBATE"),
    ("CemuNHÃ©", "COMUNHÃO"),
    ("C®NTR0Lfi niENTAL", "CONTROLE MENTAL"),
    ("DISFARCES", "DISFARCES"),
    ("DREN©", "DRENO"),
    ("DRUIDIA", "DRUIDIA"),
    ("ÊNfiRGIZACÃ©", "ENERGIZAÇÃO"),
    ("ffiUD®", "FEUDO"),
    ("Gupe", "GLIFO"),
    ("LfiXTALiems", "LEGALISMO"),
    ("IIIfiNSAGfilR® CfiLfiSTIAL", "MENSAGEIRO CELESTIAL"),
    ("NlffiBUS", "NIMBUS"),
    ("PAssAGfim ASTRAL", "PASSAGEM ASTRAL"),
    ("PfiRCfiPCÃ® DIVINA", "PERCEPÇÃO DIVINA"),
    ("QUfiRUBIA", "QUERUBIM"),
    ("RfiGENfiRACA©", "REGENERAÇÃO"),
    ("SimuiACRe", "SIMULACRO"),
    ("TfiLECINlSIA", "TELECINESIA"),
    ("0B|ETes ITIÁGices", "OBJETOS MÁGICOS"),
    ("®B|ETOS IIIAGICOS", "OBJETOS MÁGICOS"),
    ("0b|ETes II1ÁGices", "OBJETOS MÁGICOS"),
    ("TABELA oe ©Bjeres IIIÁGices:", "TABELA DE OBJETOS MÁGICOS:"),
    ("CRIANDO srus paépRi© ITENS mAcices", "CRIANDO SEUS PRÓPRIOS ITENS MÁGICOS"),
    ("P®NT©S D6", "PONTOS DE FÉ"),
    ("PONTOS DE Fe", "PONTOS DE FÉ"),
    ("AFASTAR menres -vives", "AFASTAR MORTOS-VIVOS"),
    ("Aumente DE ATRIBUTOS Físices", "AUMENTO DE ATRIBUTOS FÍSICOS"),
    ("AumfiNTe miLAGRese DG ATRIBUTOS", "AUMENTO MILAGROSO DE ATRIBUTOS"),
    ("ATIVACA® DÊ ITENS HlÁcices", "ATIVAÇÃO DE ITENS MÁGICOS"),
    ("BÊNÇÃO", "BÊNÇÃO"),
    ("CONTROLAR HIORTOS-Vivos", "CONTROLAR MORTOS-VIVOS"),
    ("CONVERSAR com PÁSSAROS E ANIMAIS", "CONVERSAR COM PÁSSAROS E ANIMAIS"),
    ("CRIAÇÃO DE ÁGUA BENTA", "CRIAÇÃO DE ÁGUA BENTA"),
    ("©UTR®S P®DfiRfiS", "OUTROS PODERES"),
    ("REGRAS e TESTES", "REGRAS E TESTES"),
    ("'TESTE DE ATRIBUT®", "TESTE DE ATRIBUTO"),
    ("Tesre FÁCIL", "TESTE FÁCIL"),
    ("TESTE DIFÍCIL", "TESTE DIFÍCIL"),
    ("CAS® ESPECIAL : FffiRCA", "CASO ESPECIAL: FORÇA"),
    ("ATRIBUT® vs. ATRIBUT®", "ATRIBUTO vs. ATRIBUTO"),
    ("SUCESSS e FRACASSO AuremÁTices", "SUCESSO E FRACASSO AUTOMÁTICOS"),
    ("SffimANDffl ATRIBUTOS", "SOMANDO ATRIBUTOS"),
    ("TESTE DE RESISTÊNCIA", "TESTE DE RESISTÊNCIA"),
    ("PERÍCIA vs. PERÍCIA", "PERÍCIA vs. PERÍCIA"),
    ("PERÍCIA vs. ATRIBUT®", "PERÍCIA vs. ATRIBUTO"),
    ("'TESTE DE PERÍCIA", "TESTE DE PERÍCIA"),
    ("TESTE oe PERÍCIA cem", "TESTE DE PERÍCIA COM MODIFICADORES"),
    ("CeniBATE", "COMBATE"),
    ("3H ATAQUES eu ACÔES", "ATAQUES OU AÇÕES"),
    ("4- CALCULA-SE es ACERTOS E DANCS", "4- CALCULA-SE OS ACERTOS E DANOS"),
    ("© ÇUfi FAZfiR Effl umA RffiDADA?", "O QUE FAZER EM UMA RODADA?"),
    ("INICIATIVA e", "INICIATIVA"),
    ("ITIeDipicADeR DE ARIHA", "MODIFICADOR DE ARMA"),
    ("IIIeDiFicADeR DE ARIHA TTIÁGICA", "MODIFICADOR DE ARMA MÁGICA"),
    ("IIIeDIFICADeR DE IIlAGIA", "MODIFICADOR DE MAGIA"),
    ("INICIATIVA NEGATIVA", "INICIATIVA NEGATIVA"),
    ("VfiL®CIDADE", "VELOCIDADE"),
    ("VAL©R DE ATAQUE E DEFESA", "VALOR DE ATAQUE E DEFESA"),
    ("DAM®", "DANO"),
    ("ACÊRTS CRÍTIC©", "ACERTO CRÍTICO"),
    ("ÍNDICE DÊ PR®TECÃ® (IP)", "ÍNDICE DE PROTEÇÃO (IP)"),
    ("DANS DE ImpAcre", "DANO DE IMPACTO"),
    ("CeiTIBATE D£SAR.II!ADe", "COMBATE DESARMADO"),
    ("III ULTIPl.es ©P® N ENTES", "MÚLTIPLOS OPONENTES"),
    ("fllúLTiPiffis ATAQUES", "MÚLTIPLOS ATAQUES"),
    ("ATAQUES A DISTANCIA", "ATAQUES À DISTÂNCIA"),
    ("ATAQues FeRA DÊ ALCANCE", "ATAQUES FORA DE ALCANCE"),
    ("RAJADA", "RAJADA"),
    ("GRANADAS", "GRANADAS"),
    ("ATAQUE LQCAUZAD®", "ATAQUE LOCALIZADO"),
    ("DesAame", "DESARME"),
    ("ATAQUE T®TAL", "ATAQUE TOTAL"),
    ("DEFESA T®TAL", "DEFESA TOTAL"),
    ("ATAQUE SURPRESA", "ATAQUE SURPRESA"),
    ("ATAQUE PELAS COSTAS", "ATAQUE PELAS COSTAS"),
    ("m i RA", "MIRA"),
    ("LUTA ÀS CEGAS", "LUTA ÀS CEGAS"),
    ("PesicA® DESVANTAJOSA", "POSIÇÃO DESVANTAJOSA"),
    ("HlÂffi ©PffiSTA", "MÃO OPOSTA"),
    ("C®mBATÊ NA® ÍIleRTAt", "COMBATE NÃO MORTAL"),
    ("AovERse", "ADVERSO"),
    ("PARALISIA", "PARALISIA"),
    ("SUFOCAR", "SUFOCAR"),
    ("QUfiDAS", "QUEDAS"),
    ("VENENffiS", "VENENOS"),
    ("DANO LecAUZAD®", "DANO LOCALIZADO"),
    ("INEVITÁVEL", "INEVITÁVEL"),
    ("H!®RRfiND®", "MORRENDO"),
    ("QUAND© SUA PRéPRlA GDADE DG ANJOS",
     "CRIANDO SUA PRÓPRIA CIDADE DE ANJOS"),
    ("PASS®", "PASSO"),

    # --- Indice (pagina 3) ---
    ("R.ECÍPERES", "RECÍPERES"),
    ("NlDIBUS", "NIMBUS"),
    ("ATRIBUTOS BAsicos", "ATRIBUTOS BÁSICOS"),
    ("APRimORAinENTOS", "APRIMORAMENTOS"),
    ("PONTOS DE Fe", "PONTOS DE FÉ"),
    ("NPCS IlHPORTANTES DE BARCELONA", "NPCS IMPORTANTES DE BARCELONA"),
    ("ANIOS PRINCIPAIS", "ANJOS PRINCIPAIS"),
    ("LANÇAS DE CHRISTOS", "LANÇAS DE CHRISTOS"),

    # --- Erros conhecidos no enunciado ---
    ("VERIflQUE DETALHCS", "VERIFIQUE DETALHES"),
    ("Nestes 2 37 anos", "Nestes 237 anos"),
    ("Protetore chamado", "Protetor chamado"),
    ("L®CAIS e CASTA", "LOCAIS E CASTA"),
    ("fisceLHA UfflA HISTéRIA ffl®RTAL", "ESCOLHA UMA HISTÓRIA MORTAL"),
    ("fisceLHA seus ATRIBUTOS", "ESCOLHA SEUS ATRIBUTOS"),
    ("EsceiHA ©s PODERES ANGELICAIS", "ESCOLHA OS PODERES ANGELICAIS"),
    ("fisceiHA ©s iNimices De PSRseNAGEm", "ESCOLHA OS INIMIGOS DO PERSONAGEM"),
    ("I. £SC®LHA A CAfflPANHA", "1. ESCOLHA A CAMPANHA"),
    ("7. Penres DE ApRimeRAmENTe", "7. PONTOS DE APRIMORAMENTO"),
    ("9. PERÍCIAS cem ARIHAS E PERÍCIAS cemuNs",
     "9. PERÍCIAS COM ARMAS E PERÍCIAS COMUNS"),
    ("10. P®NT®S DÊ VIDA E ® ÍNDICE DE PR®TECÃ®",
     "10. PONTOS DE VIDA E O ÍNDICE DE PROTEÇÃO"),
    ("11. SE ® ?ER.s®NAGem è um IIIAG®.",
     "11. SE O PERSONAGEM É UM MAGO."),
    ("DEFINA ®S P©NT©S DG IIlAGIA fi ©S F©CUS,",
     "DEFINA OS PONTOS DE MAGIA E OS FOCUS,"),
    ("12. ITENS mÁGices", "12. ITENS MÁGICOS"),
    ("13. REUNINDO ©s PERSONAGENS", "13. REUNINDO OS PERSONAGENS"),

    # --- Palavras coladas / espacos indevidos ---
    ("Urri anjo", "Um anjo"),
    ("açãd.", "ação."),
    ("medida abstraia", "medida abstrata"),
    ("átimo!", "ótimo!"),
    ("étimos médicos", "ótimos médicos"),
    ("étimos NPCs", "ótimos NPCs"),
    ("são étimos", "são ótimos"),
    ("Alifica São Pedro", "Ali fica São Pedro"),
    ("777falanges", "777 falanges"),
    ("porque^ negou", "porque negou"),
    ("Captar e,", "Captare,"),
    ("ProtetoreeNimbus", "Protetore e Nimbus"),
    ("Alighierifaz", "Alighieri faz"),
    ("umapassadinhapor", "uma passadinha por"),
    ("Joanna D 'Are", "Joanna D'Arc"),
    ("Joanna D'Are", "Joanna D'Arc"),
    ("par a o meu castelo", "para o meu castelo"),
    ("Os Protelares", "Os Protetores"),
    ("os Protelares perten", "os Protetores perten"),
    ("entre os famoso,", "entre os famosos,"),
    ("deEdwardDeVere", "de Edward De Vere"),
    ("mor a por aqui", "mora por aqui"),
    ("mora por aqui...", "mora por aqui..."),
    ("aponte dos suspiros", "a ponte dos suspiros"),
    ("ficam discuti-\ndo sobre", "ficam discutin-\ndo sobre"),
    ("amanhecerão mesmo tempo", "amanhecer ao mesmo tempo"),
    ("eleja era velho", "ele já era velho"),
    ("à servir nos céus", "a servir nos céus"),
    ("urn mausoléu", "um mausoléu"),
    ("Khepera desapa-\nreceu", "Khepera desapa-\nreceu"),
    ("porUrakabarameel", "por Urakabarameel"),
    ("açõés e reações", "ações e reações"),
    ("ao mesrno tempo", "ao mesmo tempo"),
    ("o mesrno oponente", "o mesmo oponente"),
    ("o mesmo oponente", "o mesmo oponente"),
    ("descobriram* a verdade", "descobriram a verdade"),
    ("desceram* a verdade", "descobriram a verdade"),
    ("1.118a Ordem", "1.118 a Ordem"),
    ("IPlanos \nde\nExistêncianglaterra", "Inglaterra"),
    ("sobra e Igreja", "sobre a Igreja"),
    ("sobra a região", "sobre a região"),
    ("preocupados com sobra", "preocupados com"),
    ("Washingtown", "Washington"),
    ("contínua\na usar", "continua\na usar"),
    ("contínua a usar", "continua a usar"),
    ("inciativa contra", "iniciativa contra"),
    ("de inciativa", "de iniciativa"),
    ("Ire! É também", "Lá! É também"),
    ("naNormandia", "na Normandia"),
    ("Micheal", "Michael"),
    ("snippers", "snipers"),
    ("açSo antes", "ação antes"),
    ("a segunda açSo", "a segunda ação"),
    ("desconto", "desconto"),
    ("machear seriamente", "machucar seriamente"),
    ("afaça de Mark", "a faca de Mark"),
    ("derrubar afaça", "derrubar a faca"),
    ("Cataluny a", "Catalunya"),
    ("IXfoi", "IX foi"),
    ("p/ escapar", "para escapar"),
    ("desco\"brir", "descobrir"),
    ("retomarem (em 2 horas)", "retornarem (em 2 horas)"),
    ("os pon-\ntos retomarem", "os pon-\ntos retornarem"),
    ("Anton Ia Vey", "Anton La Vey"),
    ("Fabrício GiZmo", "Fabrício Gizmo"),
    ("Norson Borrei", "Norson Botrel"),
    ("An-\ntónio Augusto Shaftiel", "An-\ntônio Augusto Shaftiel"),
    ("Gustav Doré", "Gustave Doré"),
    ("Garrei!", "Garrell"),
    ("Richard Garrell", "Richard Garrell"),
    ("útima encarnação", "última encarnação"),
    ("Vehue!,", "Vehuel,"),
    ("dejesar", "desejarás"),
    ("Não dejesar", "Não desejarás"),

    # --- 'l' OCR por '1'/'i' em numeros e palavras ---
    ("Id3, Id4, Id6, Id8, IdlO", "1d3, 1d4, 1d6, 1d8, 1d10"),
    ("l d4 significa", "1d4 significa"),
    ("Jogar l d3", "Jogar 1d3"),
    ("l d 100 quer dizer", "1d100 quer dizer"),
    ("dois dados de l O lados", "dois dados de 10 lados"),
    ("número entre l e 100", "número entre 1 e 100"),
    ("perde l PV por rodada", "perde 1 PV por rodada"),
    ("chegam a O, ele desmaia", "chegam a 0, ele desmaia"),
    ("l Poder angelical para cada l O anos",
     "1 Poder angelical para cada 10 anos"),
    ("equivale a aproximada-\nmente l O segundos",
     "equivale a aproximada-\nmente 10 segundos"),
    ("Joga-\nse l dl 00", "Joga-\nse 1d100"),
    ("Joga-se l d 100", "Joga-se 1d100"),
    ("jogada de\nIdl 00", "jogada de\n1d100"),
    ("Se a jogada de\nIdl 00", "Se a jogada de\n1d100"),
    ("[Astronomia 30]", "[Astronomia 30]"),
    ("(Joga-se l d 100", "(Joga-se 1d100"),
    ("surgiu em 1 5,000 AC", "surgiu em 15.000 AC"),
    ("há uns 15.000", "há uns 15.000"),
    ("1 5,000 AC", "15.000 AC"),
    ("em 10,000 AC", "em 10.000 AC"),
    ("em 7,500 AC", "em 7.500 AC"),
    ("823,543 keepers", "823.543 keepers"),
    ("7,777 colinas", "7.777 colinas"),
    ("em 35 DC", "em 35 DC"),
    ("4000 AC", "4000 AC"),
    ("em 4.500 AC", "em 4.500 AC"),
    ("em 206 AC", "em 206 AC"),
    ("possui 23 poderes", "possui 23 poderes"),
    ("ecolhidos da se-", "escolhidos da se-"),
    ("7pontos de Focus", "7 pontos de Focus"),
    ("2pontos em Fogo", "2 pontos em Fogo"),
    ("possui l inimigo poderoso", "possui 1 inimigo poderoso"),
    ("ponto de Aprimora-\nmento para cada 20 anos",
     "ponto de Aprimora-\nmento para cada 20 anos"),
    ("(mínimo 5)", "(mínimo 5)"),
    ("em J 202", "em 1202"),
    ("prémio de 1010 almas", "prêmio de 1010 almas"),
    ("possui l ou 2 amigos", "possui 1 ou 2 amigos"),
    ("1-1 pontos de Focus", "11 pontos de Focus"),
    ("Começa\ncom 1-1 pontos", "Começa\ncom 11 pontos"),
    ("l Omin", "10min"),
    ("max. l Omin", "máx. 10min"),
    ("até l km", "até 1km"),
    ("até l OOm2", "até 100m²"),
    ("raio de l OOm", "raio de 100m"),
    ("l OOkgs", "100kgs"),
    ("até lOOkgs", "até 100kgs"),
    ("SOkgs", "50kgs"),
    ("até SOkgs", "até 50kgs"),
    ("FR 6 e DEX 6", "FR 6 e DEX 6"),
    ("lOPVs", "10 PVs"),
    ("acumular até lOPVs", "acumular até 10 PVs"),
    ("até l O pessoas", "até 10 pessoas"),
    ("influenciar até l O pessoas", "influenciar até 10 pessoas"),
    ("(l .440km/h)", "(1.440km/h)"),
    ("3 dó pontos de dano", "3d6 pontos de dano"),
    ("l dó pontos", "1d6 pontos"),
    ("2dó pontos", "2d6 pontos"),
    ("2dó de dano", "2d6 de dano"),
    ("3 dó em lobisomens", "3d6 em lobisomens"),
    ("ld6+6", "1d6+6"),
    ("Ido,", "1d6,"),
    ("lOdó cargas", "10d6 cargas"),
    ("50+ldlO cargas", "50+1d10 cargas"),
    ("30+2dlO cargas", "30+2d10 cargas"),
    ("25+1 dó\nrodadas", "25+1d6\nrodadas"),
    ("Id6 PVs", "1d6 PVs"),
    ("l d6 de pontos", "1d6 de pontos"),
    ("l dó", "1d6"),
    ("IdlO+bônus", "1d10+bônus"),
    ("IdlO+bônus da FR", "1d10+bônus da FR"),
    ("causando IdlO+bônus", "causando 1d10+bônus"),
    ("Garras 50/60 dano IdlO+bônus", "Garras 50/60 dano 1d10+bônus"),
    ("IdlO", "1d10"),
    ("l d l O", "1d10"),
    ("j ogam l d l O", "jogam 1d10"),
    ("jogam l dl O cada", "jogam 1d10 cada"),
    ("Jogador e Mestre jogam l dl O", "Jogador e Mestre jogam 1d10"),
    ("Ele tirou 9 ficando", "Ele tirou 9 ficando"),
    ("Idl 00", "1d100"),
    ("l dl 00", "1d100"),
    ("l dl 0+2", "1d10+2"),
    ("2dl 0+2", "2d10+2"),
    ("l d 100", "1d100"),
    ("IdlOO", "1d100"),
    ("l dlOO", "1d100"),
    ("Basta rolar IdlOO", "Basta rolar 1d100"),
    ("jogue IdlO", "jogue 1d10"),
    ("No lugar de IdlOO, jogue IdlO", "No lugar de 1d100, jogue 1d10"),
    ("(l, l, 3,3,4,5,7,7,7,9)", "(1, 1, 3, 3, 4, 5, 7, 7, 7, 9)"),
    ("l O Ataques", "10 Ataques"),
    ("joga l O Ataques", "joga 10 Ataques"),

    # --- Atributos abreviados (cabecalhos) ---
    ("(C©N)", "(CON)"),
    ("FORCA (FR)", "FORÇA (FR)"),
    ("DESTREZA (DfiX)", "DESTREZA (DEX)"),
    ("ACUIDADE (AGI)", "ACUIDADE (AGI)"),
    ("INTELIGÊNCIA (INT)", "INTELIGÊNCIA (INT)"),
    ("FORCA DÊ V®NTADE (WILL)", "FORÇA DE VONTADE (WILL)"),
    ("CARISIIIA (CAR)", "CARISMA (CAR)"),
    ("PERCEPCAe (PER)", "PERCEPÇÃO (PER)"),
    ("físiculturista", "fisiculturista"),

    # --- Niveis e termos recorrentes ---
    ("Nível l:", "Nível 1:"),
    ("Nivel 1:", "Nível 1:"),
    ("Nivel 3:", "Nível 3:"),
    ("Nivel 4:", "Nível 4:"),
    ("Nivel 8:", "Nível 8:"),
    ("Nível 1:0 anjo regenera l P V", "Nível 1: o anjo regenera 1 PV"),
    ("regenera l PV", "regenera 1 PV"),
    ("regenera l P V", "regenera 1 PV"),
    ("Nível 4:0 anjo", "Nível 4: o anjo"),
    ("Nível 5:0 anjo", "Nível 5: o anjo"),
    ("Nível 7:0 anjo", "Nível 7: o anjo"),
    ("Nível 5:Permite", "Nível 5: Permite"),
    ("expontâneos", "espontâneos"),
    ("indistritíveis", "indescritíveis"),
    ("indiscritível", "indescritível"),
    ("descrevê-la", "descrevê-la"),
    ("afinesse", "afinco"),
    ("aluarem", "atuarem"),
    ("aturaram em", "atuaram em"),
    ("sensi-\nbilidade afetivarara", "sensi-\nbilidade afetiva rara"),
    ("afetivarara", "afetiva rara"),
    ("Baisea.", "Bússola."),
    ("Atraçõo.", "Atração."),
    ("hipnotisar", "hipnotizar"),
    ("magicalmente", "magicamente"),
    ("Mahlkoot", "Malkuth"),
    ("Hode (o explendor)", "Hod (o esplendor)"),
    ("explendor", "esplendor"),
    ("Giburah", "Geburah"),
    ("Hochma", "Hochmah"),
    ("inflingir", "infligir"),
    ("ninas especiais", "runas especiais"),
    ("desenha-\ndo ninas", "desenha-\ndo runas"),
    ("Óleo áe Quimera", "Óleo de Quimera"),
    ("dç ataques", "de ataques"),
    ("80% (2 braceletes) ou 30%", "80% (2 braceletes) ou 30%"),
    ("75% (2 braceletes) ou 30%", "75% (2 braceletes) ou 30%"),
    ("seu pupilos", "seus pupilos"),
    ("que seu pupilos", "que seus pupilos"),
    ("detecta-lo", "detectá-lo"),
    ("distrai-lo", "distraí-lo"),
    ("íazer outra", "fazer outra"),
    ("WÍLL do anjo", "WILL do anjo"),
    ("vs. WÍLL", "vs. WILL"),
    ("verificar seu um personagem", "verificar se um personagem"),
    ("o a intensidade", "a intensidade"),
    ("detec-\ntar exatamente o a intensidade", "detec-\ntar exatamente a intensidade"),
    ("Faz. cem que", "Faz com que"),
    ("Esquecimento. Faz", "Esquecimento. Faz"),
    ("mover ofaje-\ntos", "mover obje-\ntos"),
    ("mover ofajetos", "mover objetos"),
    ("se imune à dor", "se torna imune à dor"),
    ("O Anjo se imune", "O Anjo se torna imune"),
    ("WILL vs WILL", "WILL vs. WILL"),
    ("Vento.Q Anjo", "Vento. O Anjo"),
    ("objeto pessoa! apenas", "objeto pessoal apenas"),
    ("norma! da armadura", "normal da armadura"),
    ("bónus de+1", "bônus de +1"),
    ("Ancora do velho", "Âncora do velho"),
    ("retomar à terra", "retornar à terra"),
    ("portal par voltar", "portal para voltar"),
    ("se tomar uma maldição", "se tornar uma maldição"),
    ("a bênção pode vir a se tomar", "a bênção pode vir a se tornar"),
    ("Aphrodite", "Afrodite"),
    ("Réstia, Démeter", "Héstia, Deméter"),
    ("Démeter, Hera", "Deméter, Hera"),
    ("Aesclepius", "Asclépius"),
    ("Hefaestus", "Hefesto"),
    ("Gáudio", "Gáudio"),
    ("Anton La Vey", "Anton LaVey"),

    # --- 'bónus' / 'bônus' (PT-BR padrao usa 'bônus') ---
    ("bónus", "bônus"),
    ("demónio", "demônio"),
    ("demónios", "demônios"),
    ("milénio", "milênio"),
    ("milénios", "milênios"),
    ("génio", "gênio"),
    ("génios", "gênios"),
    ("Vénus", "Vênus"),
    ("Polónia", "Polônia"),
    ("Boémia", "Boêmia"),
    ("oxigénio", "oxigênio"),
    ("eletrônico", "eletrônico"),
    ("ténis", "tênis"),
    ("prémio", "prêmio"),
    ("trofeu", "troféu"),
    ("trofeus", "troféus"),
    ("paranóico", "paranoico"),
    ("paranóicos", "paranoicos"),
    ("heróico", "heroico"),
    ("heróicos", "heroicos"),
    ("andrógeno", "andrógino"),
    ("colónia", "colônia"),
    ("colónias", "colônias"),
    ("sémen", "sêmen"),
    ("Mesopotâmico", "mesopotâmico"),
    ("cronometro", "cronômetro"),

    # --- Cabecalhos remanescentes ---
    ("Dei DEBBI®", "DEL DEBBIO"),
    ("IIlARTfi", "MARTE"),
    ("A P®U'TICA NA CIDADE DE PRATA", "A POLÍTICA NA CIDADE DE PRATA"),
    ("I. £SC®LHA A CAMPANHA", "1. ESCOLHA A CAMPANHA"),
    ("G ARCANJffiS", "E ARCANJOS"),
    ("VAL®RÊS oe ATRIBUT®S", "VALORES DE ATRIBUTOS"),
    ("ffi QU6 es VAISRES SIGNIMCAJII?", "O QUE OS VALORES SIGNIFICAM?"),
    ("ClfiR®", "CLERO"),
    ("CfflNTAT®S", "CONTATOS"),
    ("DETÊCCA® DE IIIAGIA", "DETECÇÃO DE MAGIA"),
    ("GUARDIÃ® DE um ARTEFAT® IIIIP®RTANTE",
     "GUARDIÃO DE UM ARTEFATO IMPORTANTE"),
    ("L®CAL DE C®NTR®LE", "LOCAL DE CONTROLE"),
    ("PERTENCER A umA ESC®LA DE- HIAGIA",
     "PERTENCER A UMA ESCOLA DE MAGIA"),
    ("PERTENCER eu COHIANDAR UIHA SEITA",
     "PERTENCER OU COMANDAR UMA SEITA"),
    ("PODERES IIIÁGices:", "PODERES MÁGICOS:"),
    ("SENSO DE DlRECAO", "SENSO DE DIREÇÃO"),
    ("AFINIDADE cem PADAS", "AFINIDADE COM FADAS"),
    ("AirnA DUPLA", "ALMA DUPLA"),
    ("AmBlDÉSTRIA", "AMBIDESTRIA"),
    ("BIBUSTÉCA ARCANA", "BIBLIOTECA ARCANA"),
    ("GÁRGULA", "GÁRGULA"),
    ("PACres", "PACTOS"),
    ("PALAVRA DÊ Deus", "PALAVRA DE DEUS"),
    ("©B}fiT©s ilIÁGECes", "OBJETOS MÁGICOS"),
    ("LISTA Dg PERÍCIAS BÁSICAS:", "LISTA DE PERÍCIAS BÁSICAS:"),
    ("VALOR INICIAL", "VALOR INICIAL"),
    # Cabecalho de capitulo: linha isolada "ANGELICAIS" (pos page 48/49) ->
    # tratada via post-processo abaixo para nao colidir com "PODERES ANGELICAIS".
    ("ambidesíria", "ambidestria"),
    ("A ambidesíria afeta", "A ambidestria afeta"),
    ("em Spiriíum", "em Spiritum"),
    ("Spiriíum, e o outro", "Spiritum, e o outro"),

    # --- pontuacao / espacos ---
    ("j á ", "já "),
    ("j á\n", "já\n"),
    ("Alephia j á", "Alephia já"),
    (" ?", "?"),
    ("Email do Autor:", "E-mail do Autor:"),
    ("Email da Editora:", "E-mail da Editora:"),
]


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    original = text
    counts: dict[str, int] = {}
    for wrong, right in REPLACEMENTS:
        n = text.count(wrong)
        if n:
            text = text.replace(wrong, right)
            counts[wrong] = n

    # --- Post-processo: artefatos unicos / linha isolada ---
    # Cabecalho de capitulo isolado "ANGELICAIS" -> "PODERES ANGELICAIS"
    text = re.sub(r"(?m)^ANGELICAIS$", "PODERES ANGELICAIS", text)
    # Mojibake do cabecalho "O NOVO MUNDO" (variante com U+00A9/U+00AE)
    moj_nm = "© N®V® mUND©"
    if moj_nm in text:
        text = text.replace(moj_nm, "O NOVO MUNDO")
        counts["O NOVO MUNDO (header)"] = counts.get("O NOVO MUNDO (header)", 0) + 1
    # Remove linha de ruido de paginacao isolada "ffi"
    lines = [ln for ln in text.splitlines() if ln.strip() != "ffi"]
    text = "\n".join(lines) + ("\n" if text.endswith("\n") else "")

    OUT.write_text(text, encoding="utf-8")

    total = sum(counts.values())
    print(f"Substituicoes aplicadas (padroes distintos): {len(counts)}")
    print(f"Total de ocorrencias corrigidas: {total}")
    print(f"Caracteres antes: {len(original)} | depois: {len(text)}")
    print(f"Arquivo gerado: {OUT}")


if __name__ == "__main__":
    main()
